### ISSUE TITLE
Fails on Heroku

### ISSUE THREAD

**Issue by Swizec** [pirelenito/git-revision-webpack-plugin#19]
When I deploy to Heroku, `git-revision-plugin` fails with an error about Git repositories not being available.

I'm not sure _why_ that happens. Heroku deploys work with `git push` and to the best of my knowledge the require you to compile Webpack in a post-commit hook of some sort.

Here's my setup:

```javascript
new webpack.DefinePlugin({
            BUILD_VERSION: JSON.stringify(new GitRevisionPlugin().commithash())
        })
```

Here's the error:

```javascript
remote:        fatal: Not a git repository (or any parent up to mount point /tmp)
remote:        Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
remote:        child_process.js:526
remote:        throw err;
remote:        ^
remote:        Error: Command failed: git rev-parse HEAD
remote:        fatal: Not a git repository (or any parent up to mount point /tmp)
remote:        Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
remote:        at checkExecSyncError (child_process.js:483:13)
remote:        at execSync (child_process.js:523:13)
remote:        at module.exports (/tmp/build_18cd9bb16de5850f2c050bdfd437c15e/node_modules/git-revision-webpack-plugin/lib/helpers/run-git-command.js:25:34)
remote:        at GitRevisionPlugin.commithash (/tmp/build_18cd9bb16de5850f2c050bdfd437c15e/node_modules/git-revision-webpack-plugin/lib/index.js:58:10)
remote:        at Object.<anonymous> (/tmp/build_18cd9bb16de5850f2c050bdfd437c15e/webpack.config.babel.js:164:67)
remote:        at Module._compile (module.js:570:32)
remote:        at loader (/tmp/build_18cd9bb16de5850f2c050bdfd437c15e/node_modules/babel-register/lib/node.js:144:5)
remote:        at Object.require.extensions.(anonymous function) [as .js] (/tmp/build_18cd9bb16de5850f2c050bdfd437c15e/node_modules/babel-register/lib/node.js:154:7)
remote:        at Module.load (module.js:487:32)
remote:        at tryModuleLoad (module.js:446:12)
remote:        D, [2017-11-27T20:36:28.001511 #875] DEBUG -- : ** [Raven] Event not sent due to excluded environment: qa-3
remote:        rake aborted!
remote:        Command failed with status (1): [$(npm bin)/webpack --config webpack.config...]
remote:        /tmp/build_18cd9bb16de5850f2c050bdfd437c15e/lib/tasks/assets.rake:19:in `block (2 levels) in <top (required)>'
remote:        Tasks: TOP => assets:precompile => assets:compile_environment => assets:webpack
remote:        (See full trace by running task with --trace)

```

**Comment by pirelenito** [comment]
I haven't used Heroku in awhile, but it is possible that it has your project's content in the deployment machine, but not the git repository.

Do you use Heroku to also build your static assets as part of the deployment process?

**Comment by pirelenito** [comment]
I'm closing this for lack of activity.

Please reopen if needed.

**Comment by typhoon2099** [comment]
I have the same issue. My app is built on Heroku and is failing with the same errors. It looks like the app is being built in a directory without the git repo, just a static copy of the files.

**Comment by simonfyi** [comment]
Hey,

Did not have the time to check the code.
But in my opinions, a plugin should always work regardless the environment.

Meaning in this case when "no git" available;
`run plugin + no output`

There should be a check at the start if git is initialised and available. Otherwise return null / void.
Easy check to remove git from a project and run it in the folder.

(Also check GIT_DISCOVERY_ACROSS_FILESYSTEM on https://git-scm.com/docs/git/2.17.0)

**Comment by typhoon2099** [comment]
I agree that having an option to silently fail would be beneficial. I've reverted to getting the commit hash from an environment variable that Heroku provides (`SOURCE_VERSION`, exposed via EnvironmentPlugin), but of course this does not work during local development. I would have loved to only have had to use it if this plugin fails, then it will make it easier to rehost my code elsewhere (such as Netlify).

**Comment by bgentry** [comment]
I wrote up a minimal Webpack plugin to pull the Git SHA from `SOURCE_VERSION` when on Heroku, and to use a git command otherwise (Webpack v3, but v4 just involves changing the callback registration). It creates just a `VERSION.txt` file that contains only the SHA because that's all I wanted (and other info like tag or branch is not available within Heroku builds).

```js
var gitRevisionPlugin = new GitRevisionPlugin();
// During Heroku builds, the SOURCE_VERSION and STACK environment variables are set:
var onHeroku = process.env.SOURCE_VERSION && process.env.STACK;

// If we're on Heroku, we don't have access to the .git directory so we can't
// rely on git commands to get the version. What we *do* have during Heroku
// builds is a SOURCE_VERSION env with the git SHA of the commit being built,
// so we can use that instead to generate the version file.
function getCommitHash() {
  return onHeroku ? process.env.SOURCE_VERSION : gitRevisionPlugin.commithash();
}

// A simple webpack plugin to get the current version and output that to
// VERSION.txt in the output tree. This is inspired by the GitRevisionPlugin,
// but it is a simplified version that can work on or off Heroku.
var versionFilePlugin = {
  apply: function(compiler) {
    var version;

    compiler.plugin('compilation', function (compilation) {
      compilation.plugin('optimize-tree', function (chunks, modules, callback) {
        version = getCommitHash();
        callback();
      });
    });

    compiler.plugin('emit', function (compilation, callback) {
      compilation.assets['VERSION.txt'] = {
        source: function () {
          return version;
        },
        size: function () {
          return version.length;
        }
      }

      callback()
    });
  }
};
```

 Hope this helps somebody else! :v:

**Comment by Iuriy-Budnikov** [comment]
I added ex of the plugin for 5 webpack https://github.com/wearepush/push-starter/blob/master/config/addBuildGitVersion.js
