### ISSUE TITLE
Cannot read 'compilation' of undefined

### ISSUE THREAD

**Issue by Mossar** [pirelenito/git-revision-webpack-plugin#29]
Hello!

I try to use your plugin with Webpack 2.1.0 and I get following error:

```
C:\Projekty\web-frontend\node_modules\git-revision-webpack-plugin\lib\build-file.js:6
  compiler.hooks.compilation.tap('compilation', (compilation) => {
                ^

TypeError: Cannot read property 'compilation' of undefined
at buildFile (C:\Projekty\web-frontend\node_modules\git-revision-webpack-plugin\lib\build-file.js:6:17)
    at GitRevisionPlugin.apply (C:\Projekty\web-frontend\node_modules\git-revision-webpack-plugin\lib\index.js:30:3)
    at Compiler.apply (C:\Projekty\web-frontend\node_modules\tapable\lib\Tapable.js:375:16)
    at WebpackOptionsApply.process (C:\Projekty\web-frontend\node_modules\webpack\lib\WebpackOptionsApply.js:58:18)
    at webpack (C:\Projekty\web-frontend\node_modules\webpack\lib\webpack.js:25:48)
    at Object.<anonymous> (C:\Projekty\web-frontend\conf\browsersync.conf.js:8:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module._load (C:\Projekty\web-frontend\node_modules\gulp-hub\lib\load-subfile.js:26:32)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Projekty\web-frontend\gulp_tasks\browsersync.js:5:25)
    at Module._compile (module.js:570:32)
```

Is it possible to run it with Webpack 2?

**Comment by pirelenito** [comment]
Thanks for the reply @simonfyi ❤️

I've just added a [notice in the readme](https://github.com/pirelenito/git-revision-webpack-plugin#usage) about version compatibility and how to [use it with older versions of webpack](https://github.com/pirelenito/git-revision-webpack-plugin#outdated-webpack).

@Mossar, while you don't upgrade to webpack 4 you can use an older version of this package:

```
npm install git-revision-webpack-plugin@2.5.1
```

The only difference between that version and the latest is **webpack 4 support**.

**Comment by pirelenito** [comment]
I'll close the issue, but feel free to open it if you have move questions.
